/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Card = {
  badge?: string;
  subtitle?: string;
};

export type Hero = {
  heading?: Heading;
  description: string;
  highlights?: Array<{
    label?: string;
    title?: string;
    description?: string;
    _type: "highlight";
    _key: string;
  }>;
};

export type Heading = {
  prefix: string;
  accent: string;
};

export type SocialLinks = {
  _type: "socialLinks";
  instagram?: string;
  tiktok?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ArticleImage;
  noIndex?: boolean;
};

export type PublisherMetadata = {
  _type: "publisherMetadata";
  source?: string;
  sourceId?: string;
  intakeFolder?: string;
  bundleSha256?: string;
  createdAt?: string;
  youtubeStatus?: string;
  youtubeVideoId?: string;
  youtubeUploadDate?: string;
};

export type MigrationMetadata = {
  _type: "migrationMetadata";
  sourceSystem?: string;
  sourceId?: string;
  sourceFile?: string;
  legacyUrl?: string;
  migratedAt?: string;
  qualityFlags?: Array<string>;
};

export type HomepagePresentation = {
  _type: "homepagePresentation";
  card?: Card;
  hero?: Hero;
};

export type ArticleVideo = {
  _type: "articleVideo";
  youtubeVideoId: string;
  uploadDate: string;
  socialLinks?: SocialLinks;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ArticleImage = {
  _type: "articleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  legacyPath?: string;
};

export type ArticleBody = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  publishedAt: string;
  updatedAt: string;
  primaryTag:
    | "Mat & dryck"
    | "Loppis & second hand"
    | "Hem & inredning"
    | "Upplevelser & n\xF6jen"
    | "Utflykter & natur";
  locationTag: string;
  qualifierTag:
    | "Bageri"
    | "Restaurang"
    | "Hantverk"
    | "Husprojekt"
    | "Konserter"
    | "Musikquiz"
    | "Str\xE4nder"
    | "Utsikt"
    | "Loppisrunda"
    | "Weekend"
    | "Sommar"
    | "H\xF6st"
    | "Guide";
  tags?: Array<string>;
  body: ArticleBody;
  coverImage?: ArticleImage;
  video?: ArticleVideo;
  featured?: boolean;
  homepage?: HomepagePresentation;
  seo?: Seo;
  migration?: MigrationMetadata;
  publisherMetadata?: PublisherMetadata;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Card
  | Hero
  | Heading
  | SocialLinks
  | Seo
  | PublisherMetadata
  | MigrationMetadata
  | HomepagePresentation
  | ArticleVideo
  | SanityImageAssetReference
  | ArticleImage
  | ArticleBody
  | Article
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../gotlandstider-site/src/lib/sanity/queries.ts
// Variable: SANITY_ARTICLES_QUERY
// Query: *[    _type == "article" &&    !(_id in path("drafts.**")) &&    defined(slug.current)  ] | order(publishedAt desc, slug.current asc) {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    updatedAt,    "primaryTag": coalesce(primaryTag, tags[0]),    "locationTag": coalesce(locationTag, tags[1]),    "qualifierTag": coalesce(qualifierTag, tags[2]),    featured,    body,    "coverImage": coalesce(coverImage.asset->url, coverImage.legacyPath),    video {      youtubeVideoId,      uploadDate,      socialLinks {        "instagram": coalesce(instagram, null),        "tiktok": coalesce(tiktok, null)      }    },    homepage {      card { badge, subtitle },      hero {        heading { prefix, accent },        description,        highlights[] { _key, label, title, description }      }    },    "seo": {      "title": seo.title,      "description": seo.description,      "image": coalesce(seo.image.asset->url, seo.image.legacyPath),      "noIndex": seo.noIndex == true    },    "sourceFile": coalesce(      migration.sourceFile,      "content/articles/" + slug.current + ".md"    )  }
export type SANITY_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  updatedAt: string;
  primaryTag:
    | "Hem & inredning"
    | "Loppis & second hand"
    | "Mat & dryck"
    | "Upplevelser & n\xF6jen"
    | "Utflykter & natur";
  locationTag: string;
  qualifierTag:
    | "Bageri"
    | "Guide"
    | "Hantverk"
    | "H\xF6st"
    | "Husprojekt"
    | "Konserter"
    | "Loppisrunda"
    | "Musikquiz"
    | "Restaurang"
    | "Sommar"
    | "Str\xE4nder"
    | "Utsikt"
    | "Weekend";
  featured: boolean | null;
  body: ArticleBody;
  coverImage: string | null;
  video: {
    youtubeVideoId: string;
    uploadDate: string;
    socialLinks: {
      instagram: string | null;
      tiktok: string | null;
    } | null;
  } | null;
  homepage: {
    card: {
      badge: string | null;
      subtitle: string | null;
    } | null;
    hero: {
      heading: {
        prefix: string;
        accent: string;
      } | null;
      description: string;
      highlights: Array<{
        _key: string;
        label: string | null;
        title: string | null;
        description: string | null;
      }> | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: string | null;
    noIndex: boolean | false;
  };
  sourceFile: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "article" &&\n    !(_id in path("drafts.**")) &&\n    defined(slug.current)\n  ] | order(publishedAt desc, slug.current asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    updatedAt,\n    "primaryTag": coalesce(primaryTag, tags[0]),\n    "locationTag": coalesce(locationTag, tags[1]),\n    "qualifierTag": coalesce(qualifierTag, tags[2]),\n    featured,\n    body,\n    "coverImage": coalesce(coverImage.asset->url, coverImage.legacyPath),\n    video {\n      youtubeVideoId,\n      uploadDate,\n      socialLinks {\n        "instagram": coalesce(instagram, null),\n        "tiktok": coalesce(tiktok, null)\n      }\n    },\n    homepage {\n      card { badge, subtitle },\n      hero {\n        heading { prefix, accent },\n        description,\n        highlights[] { _key, label, title, description }\n      }\n    },\n    "seo": {\n      "title": seo.title,\n      "description": seo.description,\n      "image": coalesce(seo.image.asset->url, seo.image.legacyPath),\n      "noIndex": seo.noIndex == true\n    },\n    "sourceFile": coalesce(\n      migration.sourceFile,\n      "content/articles/" + slug.current + ".md"\n    )\n  }\n': SANITY_ARTICLES_QUERY_RESULT;
  }
}
